import { variableConfig } from 'configs'

export const authCodeExpired = Object.freeze({
  msg: {
    en: 'Your login state has expired. Please try initializing authentication again.',
    fr: 'Votre état de connexion a expiré. Veuillez réessayer d’initialiser l’authentification.',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Rediriger en arrière',
  },
})

export const changeEmail = Object.freeze({
  success: {
    en: 'Email updated!',
    fr: 'Adresse e-mail mise à jour !',
  },
  title: {
    en: 'Change your email',
    fr: 'Changer votre adresse e-mail',
  },
  email: {
    en: 'Email Address',
    fr: 'Adresse e-mail',
  },
  confirm: {
    en: 'Confirm',
    fr: 'Confirmer',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Retourner en arrière',
  },
  sendCode: {
    en: 'Send Verification Code',
    fr: 'Envoyer le code de vérification',
  },
  code: {
    en: 'Verification Code',
    fr: 'Code de vérification',
  },
  resend: {
    en: 'Resend a new code',
    fr: 'Renvoyer un nouveau code',
  },
  resent: {
    en: 'New code sent.',
    fr: 'Nouveau code envoyé.',
  },
})

export const changePassword = Object.freeze({
  title: {
    en: 'Update your password',
    fr: 'Mettez à jour votre mot de passe',
  },
  success: {
    en: 'Password updated!',
    fr: 'Mot de passe mis à jour !',
  },
  newPassword: {
    en: 'New Password',
    fr: 'Nouveau mot de passe',
  },
  confirmNewPassword: {
    en: 'Confirm New Password',
    fr: 'Confirmez le nouveau mot de passe',
  },
  confirm: {
    en: 'Confirm',
    fr: 'Confirmer',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Rediriger en arrière',
  },
})

export const consent = Object.freeze({
  title: {
    en: 'Authorize App',
    fr: "Autoriser l'application",
  },
  requestAccess: {
    en: 'is requesting access to your account.',
    fr: "demande l'accès à votre compte.",
  },
  accept: {
    en: 'Accept',
    fr: 'Accepter',
  },
  decline: {
    en: 'Decline',
    fr: 'Refuser',
  },
})

export const emailMfa = Object.freeze({
  title: {
    en: 'A verification code has been sent to your email.',
    fr: 'Un code de vérification a été envoyé à votre adresse e-mail.',
  },
  verify: {
    en: 'Verify',
    fr: 'Vérifier',
  },
  code: {
    en: 'Enter your verification code here',
    fr: 'Entrez votre code de vérification ici',
  },
  resend: {
    en: 'Resend a new code',
    fr: 'Renvoyer un nouveau code',
  },
  resent: {
    en: 'New code sent.',
    fr: 'Nouveau code envoyé.',
  },
})

export const layout = Object.freeze({
  poweredByAuth: {
    en: `Powered by ${variableConfig.systemConfig.name}`,
    fr: `Propulsé par ${variableConfig.systemConfig.name}`,
  },
})

export const managePasskey = Object.freeze({
  title: {
    en: 'Manage Passkey',
    fr: 'Gérer Passkey',
  },
  active: {
    en: 'Active Key',
    fr: 'Clé active',
  },
  loginCount: {
    en: 'Login count',
    fr: 'Compteur de connexion',
  },
  remove: {
    en: 'Remove',
    fr: 'Supprimer',
  },
  enroll: {
    en: 'Enroll',
    fr: 'Enregistrer',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Rediriger en arrière',
  },
  removeSuccess: {
    en: 'Passkey removed!',
    fr: 'Passkey supprimé !',
  },
  noPasskey: {
    en: 'No passkey found',
    fr: 'Aucun Passkey trouvé',
  },
  enrollSuccess: {
    en: 'Passkey enrolled!',
    fr: 'Passkey enregistré !',
  },
})

export const mfaEnroll = Object.freeze({
  title: {
    en: 'Select one of the MFA type',
    fr: 'Sélectionnez un type de MFA',
  },
  email: {
    en: 'Email',
    fr: 'E-mail',
  },
  otp: {
    en: 'Authenticator',
    fr: 'Authentificateur',
  },
  sms: {
    en: 'SMS',
    fr: 'message texte',
  },
})

export const otpMfa = Object.freeze({
  setup: {
    en: 'Use your authenticator app to scan the image below:',
    fr: "Utilisez votre application d'authentification pour scanner l'image ci-dessous :",
  },
  manual: {
    en: 'Unable to scan?',
    fr: 'Impossible de scanner ?',
  },
  yourKey: {
    en: 'Use the following setup key to manually configure your authenticator app.',
    fr: 'Utilisez le code suivant pour configurer manuellement votre application d\'authentification.',
  },
  code: {
    en: 'Enter the code generated by your authenticator app',
    fr: "Entrez le code généré par votre application d'authentification",
  },
  verify: {
    en: 'Verify',
    fr: 'Vérifier',
  },
  switchToEmail: {
    en: 'Receive MFA Code by Email',
    fr: 'Recevoir le code MFA par e-mail',
  },
})

export const passkeyEnroll = Object.freeze({
  title: {
    en: 'Enroll Passkey for a faster and more secure login process',
    fr: 'Enregistrer Passkey pour un processus de connexion plus rapide et plus sécurisé',
  },
  enroll: {
    en: 'Enroll',
    fr: 'Enregistrer',
  },
  skip: {
    en: 'Skip',
    fr: 'Passer',
  },
  rememberSkip: {
    en: 'Do not ask again',
    fr: 'Ne pas demander à nouveau',
  },
})

export const passwordlessCode = Object.freeze({
  title: {
    en: 'A verification code has been sent to your email.',
    fr: 'Un code de vérification a été envoyé à votre adresse e-mail.',
  },
  verify: {
    en: 'Verify',
    fr: 'Vérifier',
  },
  code: {
    en: 'Enter your verification code here',
    fr: 'Entrez votre code de vérification ici',
  },
  resend: {
    en: 'Resend a new code',
    fr: 'Renvoyer un nouveau code',
  },
  resent: {
    en: 'New code sent.',
    fr: 'Nouveau code envoyé.',
  },
})

export const resetMfa = Object.freeze({
  title: {
    en: 'Reset your MFA',
    fr: 'Réinitialisez votre MFA',
  },
  success: {
    en: 'Reset success!',
    fr: 'Réinitialisation réussie!',
  },
  desc: {
    en: 'Your current Multi-Factor Authentication (MFA) method will be reset. After this reset, you will need to set up MFA again to ensure continued secure access to your account.',
    fr: "Votre méthode actuelle d'authentification multifactorielle (MFA) sera réinitialisée. Après cette réinitialisation, vous devrez configurer à nouveau votre MFA pour garantir un accès sécurisé continu à votre compte.",
  },
  confirm: {
    en: 'Confirm',
    fr: 'Confirmer',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Rediriger en arrière',
  },
})

export const resetPassword = Object.freeze({
  title: {
    en: 'Reset your password',
    fr: 'Réinitialiser votre mot de passe',
  },
  success: {
    en: 'Password reset successful!',
    fr: 'Réinitialisation du mot de passe réussie !',
  },
  signIn: {
    en: 'Sign in',
    fr: 'Se connecter',
  },
  backSignIn: {
    en: 'Back to sign in',
    fr: 'Retour à la connexion',
  },
  desc: {
    en: 'Enter your email address, we will send you a reset code by email',
    fr: 'Entrez votre adresse e-mail, nous vous enverrons un code de réinitialisation par e-mail.',
  },
  email: {
    en: 'Email Address',
    fr: 'Adresse e-mail',
  },
  code: {
    en: 'Code',
    fr: 'Code',
  },
  password: {
    en: 'Password',
    fr: 'Mot de passe',
  },
  confirmPassword: {
    en: 'Confirm Password',
    fr: 'Confirmer le mot de passe',
  },
  send: {
    en: 'Send',
    fr: 'Envoyer',
  },
  reset: {
    en: 'Reset',
    fr: 'Réinitialiser',
  },
  resend: {
    en: 'Resend a new code',
    fr: 'Renvoyer un nouveau code',
  },
  resent: {
    en: 'New code sent.',
    fr: 'Nouveau code envoyé.',
  },
})

export const signIn = Object.freeze({
  title: {
    en: 'Authentication',
    fr: 'Authentification',
  },
  email: {
    en: 'Email',
    fr: 'Adresse e-mail',
  },
  password: {
    en: 'Password',
    fr: 'Mot de passe',
  },
  submit: {
    en: 'Login',
    fr: 'Se connecter',
  },
  signUp: {
    en: 'Create a new account',
    fr: 'Créer un nouveau compte',
  },
  passwordReset: {
    en: 'Reset password',
    fr: 'Réinitialiser le mot de passe',
  },
  githubSignIn: {
    en: 'Log in with GitHub',
    fr: 'Se connecter avec GitHub',
  },
  discordSignIn: {
    en: 'Log in with Discord',
    fr: 'Se connecter avec Discord',
  },
  oidcSignIn: {
    en: 'Log in with ',
    fr: 'Se connecter avec ',
  },
  continue: {
    en: 'Continue',
    fr: 'Continuer',
  },
  withPasskey: {
    en: 'Log in with Passkey',
    fr: 'Se connecter avec Passkey',
  },
})

export const signUp = Object.freeze({
  title: {
    en: 'Create an account',
    fr: 'Créer un compte',
  },
  email: {
    en: 'Email',
    fr: 'Adresse e-mail',
  },
  password: {
    en: 'Password',
    fr: 'Mot de passe',
  },
  confirmPassword: {
    en: 'Confirm Password',
    fr: 'Confirmer le mot de passe',
  },
  firstName: {
    en: 'First Name',
    fr: 'Prénom',
  },
  lastName: {
    en: 'Last Name',
    fr: 'Nom',
  },
  signUp: {
    en: 'Confirm',
    fr: 'Confirmer',
  },
  signIn: {
    en: 'Already have an account? Sign in',
    fr: 'Vous avez déjà un compte ? Connectez-vous.',
  },
  bySignUp: {
    en: 'By signing up, you agree to our',
    fr: 'En vous inscrivant, vous acceptez nos',
  },
  linkConnect: {
    en: 'and',
    fr: 'et',
  },
  terms: {
    en: 'Terms of Service',
    fr: 'Conditions d’utilisation',
  },
  privacyPolicy: {
    en: 'Privacy Policy',
    fr: 'Politique de confidentialité',
  },
})

export const smsMfa = Object.freeze({
  title: {
    en: 'SMS Verification',
    fr: 'Vérification par SMS',
  },
  phoneNumber: {
    en: 'Phone Number',
    fr: 'Numéro de téléphone',
  },
  code: {
    en: 'Verification Code',
    fr: 'Code de vérification',
  },
  sendCode: {
    en: 'Send code',
    fr: 'Envoyer le code',
  },
  verify: {
    en: 'Verify',
    fr: 'Vérifier',
  },
  resend: {
    en: 'Resend a new code',
    fr: 'Renvoyer un nouveau code',
  },
  resent: {
    en: 'New code sent.',
    fr: 'Nouveau code envoyé.',
  },
  switchToEmail: {
    en: 'Receive MFA Code by Email',
    fr: 'Recevoir le code MFA par e-mail',
  },
})

export const updateInfo = Object.freeze({
  title: {
    en: 'Update your info',
    fr: 'Mettre à jour vos informations',
  },
  firstName: {
    en: 'First Name',
    fr: 'Prénom',
  },
  lastName: {
    en: 'Last Name',
    fr: 'Nom',
  },
  success: {
    en: 'Info updated!',
    fr: 'Informations mises à jour !',
  },
  confirm: {
    en: 'Confirm',
    fr: 'Confirmer',
  },
  redirect: {
    en: 'Redirect back',
    fr: 'Rediriger en arrière',
  },
})

export const verifyEmail = Object.freeze({
  title: {
    en: 'Verify your email',
    fr: 'Vérifiez votre e-mail',
  },
  desc: {
    en: 'Enter your verification code received by email',
    fr: 'Entrez le code de vérification reçu par e-mail',
  },
  verify: {
    en: 'Verify',
    fr: 'Vérifier',
  },
  success: {
    en: 'Verification successful! You can close this page now.',
    fr: 'Vérification réussie ! Vous pouvez fermer cette page maintenant.',
  },
})

export const requestError = Object.freeze({
  authFailed: {
    en: 'Authentication Failed.',
    fr: "Échec de l'authentification.",
  },
  noUser: {
    en: 'No user found.',
    fr: 'Aucun utilisateur trouvé.',
  },
  disabledUser: {
    en: 'This account has been disabled.',
    fr: 'Ce compte a été désactivé.',
  },
  accountLocked: {
    en: 'Account temporarily locked due to excessive login failures.',
    fr: 'Compte temporairement bloqué en raison de trop nombreuses tentatives de connexion échouées.',
  },
  requireNewPassword: {
    en: 'Your new password can not be same as old password.',
    fr: "Votre nouveau mot de passe ne peut pas être identique à l'ancien mot de passe.",
  },
  requireNewEmail: {
    en: 'Your new email can not be same as old email.',
    fr: "Votre nouvelle adresse e-mail ne peut pas être identique à l'ancienne adresse e-mail.",
  },
  emailAlreadyVerified: {
    en: 'The email address is already verified.',
    fr: 'L\'adresse e-mail est déjà vérifiée.',
  },
  optMfaLocked: {
    en: 'Too many failed OTP verification attempts. Please try again after 30 minutes.',
    fr: 'Nombre trop élevé de tentatives échouées de vérification OTP. Veuillez réessayer dans 30 minutes.',
  },
  smsMfaLocked: {
    en: 'Too many SMS verification attempts. Please try again after 30 minutes.',
    fr: 'Trop de tentatives de vérification par SMS. Veuillez réessayer dans 30 minutes.',
  },
  emailMfaLocked: {
    en: 'Too many email verification attempts. Please try again after 30 minutes.',
    fr: 'Trop de tentatives de vérification par email. Veuillez réessayer dans 30 minutes.',
  },
  passwordResetLocked: {
    en: 'Too many password reset requests. Please try again tomorrow.',
    fr: 'Trop de demandes de réinitialisation de mot de passe. Veuillez réessayer demain.',
  },
  changeEmailLocked: {
    en: 'Too many send email change code requests. Please try again after 30 minutes.',
    fr: 'Trop de demandes de modification de code de changement d\'adresse e-mail. Veuillez réessayer dans 30 minutes.',
  },
  emailTaken: {
    en: 'The email address is already in use.',
    fr: 'Cette adresse e-mail est déjà utilisée.',
  },
  wrongCode: {
    en: 'Invalid code.',
    fr: 'Code invalide.',
  },
})

export const validateError = Object.freeze({
  passwordIsRequired: {
    en: 'Password is required!',
    fr: 'Le mot de passe est requis !',
  },
  fieldIsRequired: {
    en: 'This field is required!',
    fr: 'Ce champ est requis !',
  },
  passwordFormat: {
    en: 'Password must be at least 8 characters, contain at least one uppercase letter, one lowercase letter, one number, and one special character.',
    fr: 'Le mot de passe doit contenir au moins 8 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.',
  },
  phoneNumberIsRequired: {
    en: 'Phone number is required!',
    fr: 'Le numéro de téléphone est requis !',
  },
  wrongPhoneFormat: {
    en: 'the format must be a number up to fifteen digits in length starting with a ‘+’ with country code.',
    fr: 'Le format doit être un numéro de maximum quinze chiffres commençant par un ‘+’ avec l’indicatif du pays.',
  },
  emailIsRequired: {
    en: 'Email is required!',
    fr: "L'adresse e-mail est requise !",
  },
  wrongEmailFormat: {
    en: 'Wrong email format.',
    fr: "Format d'e-mail incorrect.",
  },
  isNotEmail: {
    en: 'Wrong email format.',
    fr: "Format d'e-mail incorrect.",
  },
  isWeakPassword: {
    en: 'Password must be at least 8 characters, contain at least one uppercase letter, one lowercase letter, one number, and one special character.',
    fr: 'Le mot de passe doit contenir au moins 8 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial.',
  },
  passwordNotMatch: {
    en: 'The password and confirm password do not match.',
    fr: 'Le mot de passe et la confirmation ne correspondent pas.',
  },
  firstNameIsEmpty: {
    en: 'First name can not be empty.',
    fr: 'Le prénom ne peut pas être vide.',
  },
  lastNameIsEmpty: {
    en: 'Last name can not be empty.',
    fr: 'Le nom de famille ne peut pas être vide.',
  },
  otpCodeLengthIssue: {
    en: 'OTP code can only be 6 digits numbers.',
    fr: 'Le code OTP ne peut être composé que de 6 chiffres.',
  },
  verificationCodeLengthIssue: {
    en: 'Verification code can only be 6 characters.',
    fr: 'Le code de vérification doit contenir 6 caractères.',
  },
})
