# -----------------------------------------------------------------------------
# Melody Auth - Development Dockerfile
# ⚠️ This is for development only. Do NOT use in production environments.
#
# You need to set the following env vars in server/.dev.vars to run this project using docker
# PG_CONNECTION_STRING=postgres://admin:admin@postgres:5432/melody-auth
# REDIS_CONNECTION_STRING=redis://redis:6379
# -----------------------------------------------------------------------------
FROM node:22

WORKDIR /app

COPY . .

WORKDIR /app/server

RUN npm ci

RUN npm run node:secret:generate

EXPOSE 8787
