export * as oauthRoute from 'routes/oauth'
export * as userRoute from 'routes/user'
export * as appRoute from 'routes/app'
export * as identityRoute from 'routes/identity'
export * as otherRoute from 'routes/other'
