name: pr-check CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]

jobs:
  root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build documentation
        run: npm run docs:build

      - name: Run linting
        run: npm run lint:check

  shared:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./shared
        run: npm ci

      - name: Check and build shared package
        working-directory: ./shared
        run: |
          npm run type:check
          npm run test:check
          npm run build

  web-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./sdks/web-sdk
        run: npm ci

      - name: Check and build web SDK
        working-directory: ./sdks/web-sdk
        run: |
          npm run type:check
          npm run test:check
          npm run build

  react-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./sdks/react-sdk
        run: npm ci

      - name: Check and build React SDK
        working-directory: ./sdks/react-sdk
        run: |
          npm run type:check
          npm run test:check
          npm run build

  vue-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./sdks/vue-sdk
        run: npm ci

      - name: Check and build Vue SDK
        working-directory: ./sdks/vue-sdk
        run: |
          npm run type:check
          npm run test:check
          npm run build

  angular-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./sdks/angular-sdk
        run: npm ci

      - name: Check and build Angular SDK
        working-directory: ./sdks/angular-sdk
        run: |
          npm run type:check
          npm run test:check
          npm run build

  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Check and test server
        working-directory: ./server
        run: |
          npm run type:check
          npm run node:secret:generate
          npm run node:saml:secret:generate
          npm run test:check:cf
          npm run test:check:node
          npm run node:secret:generate
          npm run test:check:cf-key-rotate
          npm run test:check:node-key-rotate

      - name: Build server
        working-directory: ./server
        run: npm run node:build

  admin-panel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./admin-panel
        run: npm ci

      - name: Check and test admin panel
        working-directory: ./admin-panel
        run: |
          npm run type:check
          npm run test:check

      - name: Build admin panel
        working-directory: ./admin-panel
        run: |
          npm run build
          npm run cf:build
