name: pr-check CI

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: cd ./admin-panel && npm ci
    - run: npm run build
    - run: npm run lint:check
    - run: npm run type:check
    - run: cd ./shared && npm run test:check
    - run: cd ./web-sdk && npm run test:check
    - run: cd ./react-sdk && npm run test:check
    - run: cd ./server && npm run node:secret:generate
    - run: cd ./server && npm run test:check:cf
    - run: cd ./server && npm run test:check:node
    - run: cd ./server && npm run node:secret:generate
    - run: cd ./server && npm run test:check:cf-key-rotate
    - run: cd ./server && npm run test:check:node-key-rotate
    - run: cd ./server && npm run node:build
    - run: cd ./admin-panel && npm run build
    - run: cd ./admin-panel && npm run cf:build
    - run: cd ./admin-panel && npm run test:check
