name: vue-sdk publish CI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: cd sdks/vue-sdk && npm ci

    - name: Build vue-sdk package
      run: cd sdks/vue-sdk && npm run build

    - name: Publish to npm
      run: cd sdks/vue-sdk && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}